// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package authstaff

import (
	"time"
)

const (
	// Label holds the string label denoting the authstaff type in the database.
	Label = "auth_staff"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldStaffFirstName holds the string denoting the staff_first_name field in the database.
	FieldStaffFirstName = "staff_first_name"
	// FieldStaffMiddleName holds the string denoting the staff_middle_name field in the database.
	FieldStaffMiddleName = "staff_middle_name"
	// FieldStaffLastName holds the string denoting the staff_last_name field in the database.
	FieldStaffLastName = "staff_last_name"
	// FieldStaffAddress holds the string denoting the staff_address field in the database.
	FieldStaffAddress = "staff_address"
	// FieldStaffPlace holds the string denoting the staff_place field in the database.
	FieldStaffPlace = "staff_place"
	// FieldStaffState holds the string denoting the staff_state field in the database.
	FieldStaffState = "staff_state"
	// FieldStaffPin holds the string denoting the staff_pin field in the database.
	FieldStaffPin = "staff_pin"
	// FieldStaffEmail holds the string denoting the staff_email field in the database.
	FieldStaffEmail = "staff_email"
	// FieldStaffMobile holds the string denoting the staff_mobile field in the database.
	FieldStaffMobile = "staff_mobile"
	// Table holds the table name of the authstaff in the database.
	Table = "auth_staffs"
)

// Columns holds all SQL columns for authstaff fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldStaffFirstName,
	FieldStaffMiddleName,
	FieldStaffLastName,
	FieldStaffAddress,
	FieldStaffPlace,
	FieldStaffState,
	FieldStaffPin,
	FieldStaffEmail,
	FieldStaffMobile,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// StaffFirstNameValidator is a validator for the "staff_first_name" field. It is called by the builders before save.
	StaffFirstNameValidator func(string) error
	// StaffEmailValidator is a validator for the "staff_email" field. It is called by the builders before save.
	StaffEmailValidator func(string) error
	// StaffMobileValidator is a validator for the "staff_mobile" field. It is called by the builders before save.
	StaffMobileValidator func(string) error
)
