// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package authstaff

import (
	"myeduate/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// StaffFirstName applies equality check predicate on the "staff_first_name" field. It's identical to StaffFirstNameEQ.
func StaffFirstName(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffFirstName), v))
	})
}

// StaffMiddleName applies equality check predicate on the "staff_middle_name" field. It's identical to StaffMiddleNameEQ.
func StaffMiddleName(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffMiddleName), v))
	})
}

// StaffLastName applies equality check predicate on the "staff_last_name" field. It's identical to StaffLastNameEQ.
func StaffLastName(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffLastName), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// StaffFirstNameEQ applies the EQ predicate on the "staff_first_name" field.
func StaffFirstNameEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameNEQ applies the NEQ predicate on the "staff_first_name" field.
func StaffFirstNameNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameIn applies the In predicate on the "staff_first_name" field.
func StaffFirstNameIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffFirstName), v...))
	})
}

// StaffFirstNameNotIn applies the NotIn predicate on the "staff_first_name" field.
func StaffFirstNameNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffFirstName), v...))
	})
}

// StaffFirstNameGT applies the GT predicate on the "staff_first_name" field.
func StaffFirstNameGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameGTE applies the GTE predicate on the "staff_first_name" field.
func StaffFirstNameGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameLT applies the LT predicate on the "staff_first_name" field.
func StaffFirstNameLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameLTE applies the LTE predicate on the "staff_first_name" field.
func StaffFirstNameLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameContains applies the Contains predicate on the "staff_first_name" field.
func StaffFirstNameContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameHasPrefix applies the HasPrefix predicate on the "staff_first_name" field.
func StaffFirstNameHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameHasSuffix applies the HasSuffix predicate on the "staff_first_name" field.
func StaffFirstNameHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameEqualFold applies the EqualFold predicate on the "staff_first_name" field.
func StaffFirstNameEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameContainsFold applies the ContainsFold predicate on the "staff_first_name" field.
func StaffFirstNameContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffFirstName), v))
	})
}

// StaffMiddleNameEQ applies the EQ predicate on the "staff_middle_name" field.
func StaffMiddleNameEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameNEQ applies the NEQ predicate on the "staff_middle_name" field.
func StaffMiddleNameNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameIn applies the In predicate on the "staff_middle_name" field.
func StaffMiddleNameIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffMiddleName), v...))
	})
}

// StaffMiddleNameNotIn applies the NotIn predicate on the "staff_middle_name" field.
func StaffMiddleNameNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffMiddleName), v...))
	})
}

// StaffMiddleNameGT applies the GT predicate on the "staff_middle_name" field.
func StaffMiddleNameGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameGTE applies the GTE predicate on the "staff_middle_name" field.
func StaffMiddleNameGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameLT applies the LT predicate on the "staff_middle_name" field.
func StaffMiddleNameLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameLTE applies the LTE predicate on the "staff_middle_name" field.
func StaffMiddleNameLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameContains applies the Contains predicate on the "staff_middle_name" field.
func StaffMiddleNameContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameHasPrefix applies the HasPrefix predicate on the "staff_middle_name" field.
func StaffMiddleNameHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameHasSuffix applies the HasSuffix predicate on the "staff_middle_name" field.
func StaffMiddleNameHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameEqualFold applies the EqualFold predicate on the "staff_middle_name" field.
func StaffMiddleNameEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameContainsFold applies the ContainsFold predicate on the "staff_middle_name" field.
func StaffMiddleNameContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffMiddleName), v))
	})
}

// StaffLastNameEQ applies the EQ predicate on the "staff_last_name" field.
func StaffLastNameEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameNEQ applies the NEQ predicate on the "staff_last_name" field.
func StaffLastNameNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameIn applies the In predicate on the "staff_last_name" field.
func StaffLastNameIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffLastName), v...))
	})
}

// StaffLastNameNotIn applies the NotIn predicate on the "staff_last_name" field.
func StaffLastNameNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffLastName), v...))
	})
}

// StaffLastNameGT applies the GT predicate on the "staff_last_name" field.
func StaffLastNameGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameGTE applies the GTE predicate on the "staff_last_name" field.
func StaffLastNameGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameLT applies the LT predicate on the "staff_last_name" field.
func StaffLastNameLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameLTE applies the LTE predicate on the "staff_last_name" field.
func StaffLastNameLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameContains applies the Contains predicate on the "staff_last_name" field.
func StaffLastNameContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameHasPrefix applies the HasPrefix predicate on the "staff_last_name" field.
func StaffLastNameHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameHasSuffix applies the HasSuffix predicate on the "staff_last_name" field.
func StaffLastNameHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameEqualFold applies the EqualFold predicate on the "staff_last_name" field.
func StaffLastNameEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameContainsFold applies the ContainsFold predicate on the "staff_last_name" field.
func StaffLastNameContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffLastName), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthStaff) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthStaff) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthStaff) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		p(s.Not())
	})
}
