// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package authstaff

import (
	"myeduate/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// StaffFirstName applies equality check predicate on the "staff_first_name" field. It's identical to StaffFirstNameEQ.
func StaffFirstName(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffFirstName), v))
	})
}

// StaffMiddleName applies equality check predicate on the "staff_middle_name" field. It's identical to StaffMiddleNameEQ.
func StaffMiddleName(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffMiddleName), v))
	})
}

// StaffLastName applies equality check predicate on the "staff_last_name" field. It's identical to StaffLastNameEQ.
func StaffLastName(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffLastName), v))
	})
}

// StaffAddress applies equality check predicate on the "staff_address" field. It's identical to StaffAddressEQ.
func StaffAddress(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffAddress), v))
	})
}

// StaffPlace applies equality check predicate on the "staff_place" field. It's identical to StaffPlaceEQ.
func StaffPlace(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffPlace), v))
	})
}

// StaffState applies equality check predicate on the "staff_state" field. It's identical to StaffStateEQ.
func StaffState(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffState), v))
	})
}

// StaffPin applies equality check predicate on the "staff_pin" field. It's identical to StaffPinEQ.
func StaffPin(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffPin), v))
	})
}

// StaffEmail applies equality check predicate on the "staff_email" field. It's identical to StaffEmailEQ.
func StaffEmail(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffEmail), v))
	})
}

// StaffMobile applies equality check predicate on the "staff_mobile" field. It's identical to StaffMobileEQ.
func StaffMobile(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffMobile), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// StaffFirstNameEQ applies the EQ predicate on the "staff_first_name" field.
func StaffFirstNameEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameNEQ applies the NEQ predicate on the "staff_first_name" field.
func StaffFirstNameNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameIn applies the In predicate on the "staff_first_name" field.
func StaffFirstNameIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffFirstName), v...))
	})
}

// StaffFirstNameNotIn applies the NotIn predicate on the "staff_first_name" field.
func StaffFirstNameNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffFirstName), v...))
	})
}

// StaffFirstNameGT applies the GT predicate on the "staff_first_name" field.
func StaffFirstNameGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameGTE applies the GTE predicate on the "staff_first_name" field.
func StaffFirstNameGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameLT applies the LT predicate on the "staff_first_name" field.
func StaffFirstNameLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameLTE applies the LTE predicate on the "staff_first_name" field.
func StaffFirstNameLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameContains applies the Contains predicate on the "staff_first_name" field.
func StaffFirstNameContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameHasPrefix applies the HasPrefix predicate on the "staff_first_name" field.
func StaffFirstNameHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameHasSuffix applies the HasSuffix predicate on the "staff_first_name" field.
func StaffFirstNameHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameEqualFold applies the EqualFold predicate on the "staff_first_name" field.
func StaffFirstNameEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffFirstName), v))
	})
}

// StaffFirstNameContainsFold applies the ContainsFold predicate on the "staff_first_name" field.
func StaffFirstNameContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffFirstName), v))
	})
}

// StaffMiddleNameEQ applies the EQ predicate on the "staff_middle_name" field.
func StaffMiddleNameEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameNEQ applies the NEQ predicate on the "staff_middle_name" field.
func StaffMiddleNameNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameIn applies the In predicate on the "staff_middle_name" field.
func StaffMiddleNameIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffMiddleName), v...))
	})
}

// StaffMiddleNameNotIn applies the NotIn predicate on the "staff_middle_name" field.
func StaffMiddleNameNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffMiddleName), v...))
	})
}

// StaffMiddleNameGT applies the GT predicate on the "staff_middle_name" field.
func StaffMiddleNameGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameGTE applies the GTE predicate on the "staff_middle_name" field.
func StaffMiddleNameGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameLT applies the LT predicate on the "staff_middle_name" field.
func StaffMiddleNameLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameLTE applies the LTE predicate on the "staff_middle_name" field.
func StaffMiddleNameLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameContains applies the Contains predicate on the "staff_middle_name" field.
func StaffMiddleNameContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameHasPrefix applies the HasPrefix predicate on the "staff_middle_name" field.
func StaffMiddleNameHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameHasSuffix applies the HasSuffix predicate on the "staff_middle_name" field.
func StaffMiddleNameHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameEqualFold applies the EqualFold predicate on the "staff_middle_name" field.
func StaffMiddleNameEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffMiddleName), v))
	})
}

// StaffMiddleNameContainsFold applies the ContainsFold predicate on the "staff_middle_name" field.
func StaffMiddleNameContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffMiddleName), v))
	})
}

// StaffLastNameEQ applies the EQ predicate on the "staff_last_name" field.
func StaffLastNameEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameNEQ applies the NEQ predicate on the "staff_last_name" field.
func StaffLastNameNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameIn applies the In predicate on the "staff_last_name" field.
func StaffLastNameIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffLastName), v...))
	})
}

// StaffLastNameNotIn applies the NotIn predicate on the "staff_last_name" field.
func StaffLastNameNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffLastName), v...))
	})
}

// StaffLastNameGT applies the GT predicate on the "staff_last_name" field.
func StaffLastNameGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameGTE applies the GTE predicate on the "staff_last_name" field.
func StaffLastNameGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameLT applies the LT predicate on the "staff_last_name" field.
func StaffLastNameLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameLTE applies the LTE predicate on the "staff_last_name" field.
func StaffLastNameLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameContains applies the Contains predicate on the "staff_last_name" field.
func StaffLastNameContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameHasPrefix applies the HasPrefix predicate on the "staff_last_name" field.
func StaffLastNameHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameHasSuffix applies the HasSuffix predicate on the "staff_last_name" field.
func StaffLastNameHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameEqualFold applies the EqualFold predicate on the "staff_last_name" field.
func StaffLastNameEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffLastName), v))
	})
}

// StaffLastNameContainsFold applies the ContainsFold predicate on the "staff_last_name" field.
func StaffLastNameContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffLastName), v))
	})
}

// StaffAddressEQ applies the EQ predicate on the "staff_address" field.
func StaffAddressEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffAddress), v))
	})
}

// StaffAddressNEQ applies the NEQ predicate on the "staff_address" field.
func StaffAddressNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffAddress), v))
	})
}

// StaffAddressIn applies the In predicate on the "staff_address" field.
func StaffAddressIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffAddress), v...))
	})
}

// StaffAddressNotIn applies the NotIn predicate on the "staff_address" field.
func StaffAddressNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffAddress), v...))
	})
}

// StaffAddressGT applies the GT predicate on the "staff_address" field.
func StaffAddressGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffAddress), v))
	})
}

// StaffAddressGTE applies the GTE predicate on the "staff_address" field.
func StaffAddressGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffAddress), v))
	})
}

// StaffAddressLT applies the LT predicate on the "staff_address" field.
func StaffAddressLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffAddress), v))
	})
}

// StaffAddressLTE applies the LTE predicate on the "staff_address" field.
func StaffAddressLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffAddress), v))
	})
}

// StaffAddressContains applies the Contains predicate on the "staff_address" field.
func StaffAddressContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffAddress), v))
	})
}

// StaffAddressHasPrefix applies the HasPrefix predicate on the "staff_address" field.
func StaffAddressHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffAddress), v))
	})
}

// StaffAddressHasSuffix applies the HasSuffix predicate on the "staff_address" field.
func StaffAddressHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffAddress), v))
	})
}

// StaffAddressEqualFold applies the EqualFold predicate on the "staff_address" field.
func StaffAddressEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffAddress), v))
	})
}

// StaffAddressContainsFold applies the ContainsFold predicate on the "staff_address" field.
func StaffAddressContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffAddress), v))
	})
}

// StaffPlaceEQ applies the EQ predicate on the "staff_place" field.
func StaffPlaceEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffPlace), v))
	})
}

// StaffPlaceNEQ applies the NEQ predicate on the "staff_place" field.
func StaffPlaceNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffPlace), v))
	})
}

// StaffPlaceIn applies the In predicate on the "staff_place" field.
func StaffPlaceIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffPlace), v...))
	})
}

// StaffPlaceNotIn applies the NotIn predicate on the "staff_place" field.
func StaffPlaceNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffPlace), v...))
	})
}

// StaffPlaceGT applies the GT predicate on the "staff_place" field.
func StaffPlaceGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffPlace), v))
	})
}

// StaffPlaceGTE applies the GTE predicate on the "staff_place" field.
func StaffPlaceGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffPlace), v))
	})
}

// StaffPlaceLT applies the LT predicate on the "staff_place" field.
func StaffPlaceLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffPlace), v))
	})
}

// StaffPlaceLTE applies the LTE predicate on the "staff_place" field.
func StaffPlaceLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffPlace), v))
	})
}

// StaffPlaceContains applies the Contains predicate on the "staff_place" field.
func StaffPlaceContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffPlace), v))
	})
}

// StaffPlaceHasPrefix applies the HasPrefix predicate on the "staff_place" field.
func StaffPlaceHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffPlace), v))
	})
}

// StaffPlaceHasSuffix applies the HasSuffix predicate on the "staff_place" field.
func StaffPlaceHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffPlace), v))
	})
}

// StaffPlaceEqualFold applies the EqualFold predicate on the "staff_place" field.
func StaffPlaceEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffPlace), v))
	})
}

// StaffPlaceContainsFold applies the ContainsFold predicate on the "staff_place" field.
func StaffPlaceContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffPlace), v))
	})
}

// StaffStateEQ applies the EQ predicate on the "staff_state" field.
func StaffStateEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffState), v))
	})
}

// StaffStateNEQ applies the NEQ predicate on the "staff_state" field.
func StaffStateNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffState), v))
	})
}

// StaffStateIn applies the In predicate on the "staff_state" field.
func StaffStateIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffState), v...))
	})
}

// StaffStateNotIn applies the NotIn predicate on the "staff_state" field.
func StaffStateNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffState), v...))
	})
}

// StaffStateGT applies the GT predicate on the "staff_state" field.
func StaffStateGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffState), v))
	})
}

// StaffStateGTE applies the GTE predicate on the "staff_state" field.
func StaffStateGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffState), v))
	})
}

// StaffStateLT applies the LT predicate on the "staff_state" field.
func StaffStateLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffState), v))
	})
}

// StaffStateLTE applies the LTE predicate on the "staff_state" field.
func StaffStateLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffState), v))
	})
}

// StaffStateContains applies the Contains predicate on the "staff_state" field.
func StaffStateContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffState), v))
	})
}

// StaffStateHasPrefix applies the HasPrefix predicate on the "staff_state" field.
func StaffStateHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffState), v))
	})
}

// StaffStateHasSuffix applies the HasSuffix predicate on the "staff_state" field.
func StaffStateHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffState), v))
	})
}

// StaffStateEqualFold applies the EqualFold predicate on the "staff_state" field.
func StaffStateEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffState), v))
	})
}

// StaffStateContainsFold applies the ContainsFold predicate on the "staff_state" field.
func StaffStateContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffState), v))
	})
}

// StaffPinEQ applies the EQ predicate on the "staff_pin" field.
func StaffPinEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffPin), v))
	})
}

// StaffPinNEQ applies the NEQ predicate on the "staff_pin" field.
func StaffPinNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffPin), v))
	})
}

// StaffPinIn applies the In predicate on the "staff_pin" field.
func StaffPinIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffPin), v...))
	})
}

// StaffPinNotIn applies the NotIn predicate on the "staff_pin" field.
func StaffPinNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffPin), v...))
	})
}

// StaffPinGT applies the GT predicate on the "staff_pin" field.
func StaffPinGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffPin), v))
	})
}

// StaffPinGTE applies the GTE predicate on the "staff_pin" field.
func StaffPinGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffPin), v))
	})
}

// StaffPinLT applies the LT predicate on the "staff_pin" field.
func StaffPinLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffPin), v))
	})
}

// StaffPinLTE applies the LTE predicate on the "staff_pin" field.
func StaffPinLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffPin), v))
	})
}

// StaffPinContains applies the Contains predicate on the "staff_pin" field.
func StaffPinContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffPin), v))
	})
}

// StaffPinHasPrefix applies the HasPrefix predicate on the "staff_pin" field.
func StaffPinHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffPin), v))
	})
}

// StaffPinHasSuffix applies the HasSuffix predicate on the "staff_pin" field.
func StaffPinHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffPin), v))
	})
}

// StaffPinEqualFold applies the EqualFold predicate on the "staff_pin" field.
func StaffPinEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffPin), v))
	})
}

// StaffPinContainsFold applies the ContainsFold predicate on the "staff_pin" field.
func StaffPinContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffPin), v))
	})
}

// StaffEmailEQ applies the EQ predicate on the "staff_email" field.
func StaffEmailEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffEmail), v))
	})
}

// StaffEmailNEQ applies the NEQ predicate on the "staff_email" field.
func StaffEmailNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffEmail), v))
	})
}

// StaffEmailIn applies the In predicate on the "staff_email" field.
func StaffEmailIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffEmail), v...))
	})
}

// StaffEmailNotIn applies the NotIn predicate on the "staff_email" field.
func StaffEmailNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffEmail), v...))
	})
}

// StaffEmailGT applies the GT predicate on the "staff_email" field.
func StaffEmailGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffEmail), v))
	})
}

// StaffEmailGTE applies the GTE predicate on the "staff_email" field.
func StaffEmailGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffEmail), v))
	})
}

// StaffEmailLT applies the LT predicate on the "staff_email" field.
func StaffEmailLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffEmail), v))
	})
}

// StaffEmailLTE applies the LTE predicate on the "staff_email" field.
func StaffEmailLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffEmail), v))
	})
}

// StaffEmailContains applies the Contains predicate on the "staff_email" field.
func StaffEmailContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffEmail), v))
	})
}

// StaffEmailHasPrefix applies the HasPrefix predicate on the "staff_email" field.
func StaffEmailHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffEmail), v))
	})
}

// StaffEmailHasSuffix applies the HasSuffix predicate on the "staff_email" field.
func StaffEmailHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffEmail), v))
	})
}

// StaffEmailEqualFold applies the EqualFold predicate on the "staff_email" field.
func StaffEmailEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffEmail), v))
	})
}

// StaffEmailContainsFold applies the ContainsFold predicate on the "staff_email" field.
func StaffEmailContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffEmail), v))
	})
}

// StaffMobileEQ applies the EQ predicate on the "staff_mobile" field.
func StaffMobileEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStaffMobile), v))
	})
}

// StaffMobileNEQ applies the NEQ predicate on the "staff_mobile" field.
func StaffMobileNEQ(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStaffMobile), v))
	})
}

// StaffMobileIn applies the In predicate on the "staff_mobile" field.
func StaffMobileIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStaffMobile), v...))
	})
}

// StaffMobileNotIn applies the NotIn predicate on the "staff_mobile" field.
func StaffMobileNotIn(vs ...string) predicate.AuthStaff {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AuthStaff(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStaffMobile), v...))
	})
}

// StaffMobileGT applies the GT predicate on the "staff_mobile" field.
func StaffMobileGT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStaffMobile), v))
	})
}

// StaffMobileGTE applies the GTE predicate on the "staff_mobile" field.
func StaffMobileGTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStaffMobile), v))
	})
}

// StaffMobileLT applies the LT predicate on the "staff_mobile" field.
func StaffMobileLT(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStaffMobile), v))
	})
}

// StaffMobileLTE applies the LTE predicate on the "staff_mobile" field.
func StaffMobileLTE(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStaffMobile), v))
	})
}

// StaffMobileContains applies the Contains predicate on the "staff_mobile" field.
func StaffMobileContains(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStaffMobile), v))
	})
}

// StaffMobileHasPrefix applies the HasPrefix predicate on the "staff_mobile" field.
func StaffMobileHasPrefix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStaffMobile), v))
	})
}

// StaffMobileHasSuffix applies the HasSuffix predicate on the "staff_mobile" field.
func StaffMobileHasSuffix(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStaffMobile), v))
	})
}

// StaffMobileEqualFold applies the EqualFold predicate on the "staff_mobile" field.
func StaffMobileEqualFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStaffMobile), v))
	})
}

// StaffMobileContainsFold applies the ContainsFold predicate on the "staff_mobile" field.
func StaffMobileContainsFold(v string) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStaffMobile), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthStaff) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthStaff) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthStaff) predicate.AuthStaff {
	return predicate.AuthStaff(func(s *sql.Selector) {
		p(s.Not())
	})
}
