// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package myeduate

import (
	"myeduate/ent/customtypes"
	"myeduate/ent/schema/pulid"
	"time"
)

type CustData struct {
	CustomerName string   `json:"customer_name"`
	ID           pulid.ID `json:"id"`
}

type InstData struct {
	InstName string   `json:"Inst_name"`
	ID       pulid.ID `json:"id"`
}

// MstCustomerWhereInput is used for filtering MstCustomer objects.
// Input was generated by ent.
type MstCustomerWhereInput struct {
	Not *MstCustomerWhereInput   `json:"not"`
	And []*MstCustomerWhereInput `json:"and"`
	Or  []*MstCustomerWhereInput `json:"or"`
	// created_at field predicates
	CreatedAt      *time.Time   `json:"createdAt"`
	CreatedAtNeq   *time.Time   `json:"createdAtNEQ"`
	CreatedAtIn    []*time.Time `json:"createdAtIn"`
	CreatedAtNotIn []*time.Time `json:"createdAtNotIn"`
	CreatedAtGt    *time.Time   `json:"createdAtGT"`
	CreatedAtGte   *time.Time   `json:"createdAtGTE"`
	CreatedAtLt    *time.Time   `json:"createdAtLT"`
	CreatedAtLte   *time.Time   `json:"createdAtLTE"`
	// updated_at field predicates
	UpdatedAt      *time.Time   `json:"updatedAt"`
	UpdatedAtNeq   *time.Time   `json:"updatedAtNEQ"`
	UpdatedAtIn    []*time.Time `json:"updatedAtIn"`
	UpdatedAtNotIn []*time.Time `json:"updatedAtNotIn"`
	UpdatedAtGt    *time.Time   `json:"updatedAtGT"`
	UpdatedAtGte   *time.Time   `json:"updatedAtGTE"`
	UpdatedAtLt    *time.Time   `json:"updatedAtLT"`
	UpdatedAtLte   *time.Time   `json:"updatedAtLTE"`
	// cust_code field predicates
	CustCode             *string  `json:"custCode"`
	CustCodeNeq          *string  `json:"custCodeNEQ"`
	CustCodeIn           []string `json:"custCodeIn"`
	CustCodeNotIn        []string `json:"custCodeNotIn"`
	CustCodeGt           *string  `json:"custCodeGT"`
	CustCodeGte          *string  `json:"custCodeGTE"`
	CustCodeLt           *string  `json:"custCodeLT"`
	CustCodeLte          *string  `json:"custCodeLTE"`
	CustCodeContains     *string  `json:"custCodeContains"`
	CustCodeHasPrefix    *string  `json:"custCodeHasPrefix"`
	CustCodeHasSuffix    *string  `json:"custCodeHasSuffix"`
	CustCodeEqualFold    *string  `json:"custCodeEqualFold"`
	CustCodeContainsFold *string  `json:"custCodeContainsFold"`
	// cust_name field predicates
	CustName             *string  `json:"custName"`
	CustNameNeq          *string  `json:"custNameNEQ"`
	CustNameIn           []string `json:"custNameIn"`
	CustNameNotIn        []string `json:"custNameNotIn"`
	CustNameGt           *string  `json:"custNameGT"`
	CustNameGte          *string  `json:"custNameGTE"`
	CustNameLt           *string  `json:"custNameLT"`
	CustNameLte          *string  `json:"custNameLTE"`
	CustNameContains     *string  `json:"custNameContains"`
	CustNameHasPrefix    *string  `json:"custNameHasPrefix"`
	CustNameHasSuffix    *string  `json:"custNameHasSuffix"`
	CustNameEqualFold    *string  `json:"custNameEqualFold"`
	CustNameContainsFold *string  `json:"custNameContainsFold"`
	// cust_address field predicates
	CustAddress             *string  `json:"custAddress"`
	CustAddressNeq          *string  `json:"custAddressNEQ"`
	CustAddressIn           []string `json:"custAddressIn"`
	CustAddressNotIn        []string `json:"custAddressNotIn"`
	CustAddressGt           *string  `json:"custAddressGT"`
	CustAddressGte          *string  `json:"custAddressGTE"`
	CustAddressLt           *string  `json:"custAddressLT"`
	CustAddressLte          *string  `json:"custAddressLTE"`
	CustAddressContains     *string  `json:"custAddressContains"`
	CustAddressHasPrefix    *string  `json:"custAddressHasPrefix"`
	CustAddressHasSuffix    *string  `json:"custAddressHasSuffix"`
	CustAddressEqualFold    *string  `json:"custAddressEqualFold"`
	CustAddressContainsFold *string  `json:"custAddressContainsFold"`
	// cust_place field predicates
	CustPlace             *string  `json:"custPlace"`
	CustPlaceNeq          *string  `json:"custPlaceNEQ"`
	CustPlaceIn           []string `json:"custPlaceIn"`
	CustPlaceNotIn        []string `json:"custPlaceNotIn"`
	CustPlaceGt           *string  `json:"custPlaceGT"`
	CustPlaceGte          *string  `json:"custPlaceGTE"`
	CustPlaceLt           *string  `json:"custPlaceLT"`
	CustPlaceLte          *string  `json:"custPlaceLTE"`
	CustPlaceContains     *string  `json:"custPlaceContains"`
	CustPlaceHasPrefix    *string  `json:"custPlaceHasPrefix"`
	CustPlaceHasSuffix    *string  `json:"custPlaceHasSuffix"`
	CustPlaceEqualFold    *string  `json:"custPlaceEqualFold"`
	CustPlaceContainsFold *string  `json:"custPlaceContainsFold"`
	// cust_state field predicates
	CustState             *string  `json:"custState"`
	CustStateNeq          *string  `json:"custStateNEQ"`
	CustStateIn           []string `json:"custStateIn"`
	CustStateNotIn        []string `json:"custStateNotIn"`
	CustStateGt           *string  `json:"custStateGT"`
	CustStateGte          *string  `json:"custStateGTE"`
	CustStateLt           *string  `json:"custStateLT"`
	CustStateLte          *string  `json:"custStateLTE"`
	CustStateContains     *string  `json:"custStateContains"`
	CustStateHasPrefix    *string  `json:"custStateHasPrefix"`
	CustStateHasSuffix    *string  `json:"custStateHasSuffix"`
	CustStateEqualFold    *string  `json:"custStateEqualFold"`
	CustStateContainsFold *string  `json:"custStateContainsFold"`
	// cust_pin field predicates
	CustPin             *string  `json:"custPin"`
	CustPinNeq          *string  `json:"custPinNEQ"`
	CustPinIn           []string `json:"custPinIn"`
	CustPinNotIn        []string `json:"custPinNotIn"`
	CustPinGt           *string  `json:"custPinGT"`
	CustPinGte          *string  `json:"custPinGTE"`
	CustPinLt           *string  `json:"custPinLT"`
	CustPinLte          *string  `json:"custPinLTE"`
	CustPinContains     *string  `json:"custPinContains"`
	CustPinHasPrefix    *string  `json:"custPinHasPrefix"`
	CustPinHasSuffix    *string  `json:"custPinHasSuffix"`
	CustPinEqualFold    *string  `json:"custPinEqualFold"`
	CustPinContainsFold *string  `json:"custPinContainsFold"`
	// cust_contact_person field predicates
	CustContactPerson             *string  `json:"custContactPerson"`
	CustContactPersonNeq          *string  `json:"custContactPersonNEQ"`
	CustContactPersonIn           []string `json:"custContactPersonIn"`
	CustContactPersonNotIn        []string `json:"custContactPersonNotIn"`
	CustContactPersonGt           *string  `json:"custContactPersonGT"`
	CustContactPersonGte          *string  `json:"custContactPersonGTE"`
	CustContactPersonLt           *string  `json:"custContactPersonLT"`
	CustContactPersonLte          *string  `json:"custContactPersonLTE"`
	CustContactPersonContains     *string  `json:"custContactPersonContains"`
	CustContactPersonHasPrefix    *string  `json:"custContactPersonHasPrefix"`
	CustContactPersonHasSuffix    *string  `json:"custContactPersonHasSuffix"`
	CustContactPersonEqualFold    *string  `json:"custContactPersonEqualFold"`
	CustContactPersonContainsFold *string  `json:"custContactPersonContainsFold"`
	// cust_phone field predicates
	CustPhone             *string  `json:"custPhone"`
	CustPhoneNeq          *string  `json:"custPhoneNEQ"`
	CustPhoneIn           []string `json:"custPhoneIn"`
	CustPhoneNotIn        []string `json:"custPhoneNotIn"`
	CustPhoneGt           *string  `json:"custPhoneGT"`
	CustPhoneGte          *string  `json:"custPhoneGTE"`
	CustPhoneLt           *string  `json:"custPhoneLT"`
	CustPhoneLte          *string  `json:"custPhoneLTE"`
	CustPhoneContains     *string  `json:"custPhoneContains"`
	CustPhoneHasPrefix    *string  `json:"custPhoneHasPrefix"`
	CustPhoneHasSuffix    *string  `json:"custPhoneHasSuffix"`
	CustPhoneEqualFold    *string  `json:"custPhoneEqualFold"`
	CustPhoneContainsFold *string  `json:"custPhoneContainsFold"`
	// cust_email field predicates
	CustEmail             *string  `json:"custEmail"`
	CustEmailNeq          *string  `json:"custEmailNEQ"`
	CustEmailIn           []string `json:"custEmailIn"`
	CustEmailNotIn        []string `json:"custEmailNotIn"`
	CustEmailGt           *string  `json:"custEmailGT"`
	CustEmailGte          *string  `json:"custEmailGTE"`
	CustEmailLt           *string  `json:"custEmailLT"`
	CustEmailLte          *string  `json:"custEmailLTE"`
	CustEmailContains     *string  `json:"custEmailContains"`
	CustEmailHasPrefix    *string  `json:"custEmailHasPrefix"`
	CustEmailHasSuffix    *string  `json:"custEmailHasSuffix"`
	CustEmailEqualFold    *string  `json:"custEmailEqualFold"`
	CustEmailContainsFold *string  `json:"custEmailContainsFold"`
	// cust_mobile field predicates
	CustMobile             *string  `json:"custMobile"`
	CustMobileNeq          *string  `json:"custMobileNEQ"`
	CustMobileIn           []string `json:"custMobileIn"`
	CustMobileNotIn        []string `json:"custMobileNotIn"`
	CustMobileGt           *string  `json:"custMobileGT"`
	CustMobileGte          *string  `json:"custMobileGTE"`
	CustMobileLt           *string  `json:"custMobileLT"`
	CustMobileLte          *string  `json:"custMobileLTE"`
	CustMobileContains     *string  `json:"custMobileContains"`
	CustMobileHasPrefix    *string  `json:"custMobileHasPrefix"`
	CustMobileHasSuffix    *string  `json:"custMobileHasSuffix"`
	CustMobileEqualFold    *string  `json:"custMobileEqualFold"`
	CustMobileContainsFold *string  `json:"custMobileContainsFold"`
	// cust_url field predicates
	CustURL             *string  `json:"custURL"`
	CustURLNeq          *string  `json:"custURLNEQ"`
	CustURLIn           []string `json:"custURLIn"`
	CustURLNotIn        []string `json:"custURLNotIn"`
	CustURLGt           *string  `json:"custURLGT"`
	CustURLGte          *string  `json:"custURLGTE"`
	CustURLLt           *string  `json:"custURLLT"`
	CustURLLte          *string  `json:"custURLLTE"`
	CustURLContains     *string  `json:"custURLContains"`
	CustURLHasPrefix    *string  `json:"custURLHasPrefix"`
	CustURLHasSuffix    *string  `json:"custURLHasSuffix"`
	CustURLEqualFold    *string  `json:"custURLEqualFold"`
	CustURLContainsFold *string  `json:"custURLContainsFold"`
	// cust_banner_1 field predicates
	CustBanner1             *string  `json:"custBanner1"`
	CustBanner1neq          *string  `json:"custBanner1NEQ"`
	CustBanner1In           []string `json:"custBanner1In"`
	CustBanner1NotIn        []string `json:"custBanner1NotIn"`
	CustBanner1gt           *string  `json:"custBanner1GT"`
	CustBanner1gte          *string  `json:"custBanner1GTE"`
	CustBanner1lt           *string  `json:"custBanner1LT"`
	CustBanner1lte          *string  `json:"custBanner1LTE"`
	CustBanner1Contains     *string  `json:"custBanner1Contains"`
	CustBanner1HasPrefix    *string  `json:"custBanner1HasPrefix"`
	CustBanner1HasSuffix    *string  `json:"custBanner1HasSuffix"`
	CustBanner1EqualFold    *string  `json:"custBanner1EqualFold"`
	CustBanner1ContainsFold *string  `json:"custBanner1ContainsFold"`
	// cust_banner_2 field predicates
	CustBanner2             *string  `json:"custBanner2"`
	CustBanner2neq          *string  `json:"custBanner2NEQ"`
	CustBanner2In           []string `json:"custBanner2In"`
	CustBanner2NotIn        []string `json:"custBanner2NotIn"`
	CustBanner2gt           *string  `json:"custBanner2GT"`
	CustBanner2gte          *string  `json:"custBanner2GTE"`
	CustBanner2lt           *string  `json:"custBanner2LT"`
	CustBanner2lte          *string  `json:"custBanner2LTE"`
	CustBanner2Contains     *string  `json:"custBanner2Contains"`
	CustBanner2HasPrefix    *string  `json:"custBanner2HasPrefix"`
	CustBanner2HasSuffix    *string  `json:"custBanner2HasSuffix"`
	CustBanner2EqualFold    *string  `json:"custBanner2EqualFold"`
	CustBanner2ContainsFold *string  `json:"custBanner2ContainsFold"`
	// cust_logo_url field predicates
	CustLogoURL             *string  `json:"custLogoURL"`
	CustLogoURLNeq          *string  `json:"custLogoURLNEQ"`
	CustLogoURLIn           []string `json:"custLogoURLIn"`
	CustLogoURLNotIn        []string `json:"custLogoURLNotIn"`
	CustLogoURLGt           *string  `json:"custLogoURLGT"`
	CustLogoURLGte          *string  `json:"custLogoURLGTE"`
	CustLogoURLLt           *string  `json:"custLogoURLLT"`
	CustLogoURLLte          *string  `json:"custLogoURLLTE"`
	CustLogoURLContains     *string  `json:"custLogoURLContains"`
	CustLogoURLHasPrefix    *string  `json:"custLogoURLHasPrefix"`
	CustLogoURLHasSuffix    *string  `json:"custLogoURLHasSuffix"`
	CustLogoURLEqualFold    *string  `json:"custLogoURLEqualFold"`
	CustLogoURLContainsFold *string  `json:"custLogoURLContainsFold"`
	// cust_is_active field predicates
	CustIsActive      *customtypes.IsActive  `json:"custIsActive"`
	CustIsActiveNeq   *customtypes.IsActive  `json:"custIsActiveNEQ"`
	CustIsActiveIn    []customtypes.IsActive `json:"custIsActiveIn"`
	CustIsActiveNotIn []customtypes.IsActive `json:"custIsActiveNotIn"`
	// cust_status field predicates
	CustStatus             *string  `json:"custStatus"`
	CustStatusNeq          *string  `json:"custStatusNEQ"`
	CustStatusIn           []string `json:"custStatusIn"`
	CustStatusNotIn        []string `json:"custStatusNotIn"`
	CustStatusGt           *string  `json:"custStatusGT"`
	CustStatusGte          *string  `json:"custStatusGTE"`
	CustStatusLt           *string  `json:"custStatusLT"`
	CustStatusLte          *string  `json:"custStatusLTE"`
	CustStatusContains     *string  `json:"custStatusContains"`
	CustStatusHasPrefix    *string  `json:"custStatusHasPrefix"`
	CustStatusHasSuffix    *string  `json:"custStatusHasSuffix"`
	CustStatusEqualFold    *string  `json:"custStatusEqualFold"`
	CustStatusContainsFold *string  `json:"custStatusContainsFold"`
	// cust_num_inst field predicates
	CustNumInst      *int  `json:"custNumInst"`
	CustNumInstNeq   *int  `json:"custNumInstNEQ"`
	CustNumInstIn    []int `json:"custNumInstIn"`
	CustNumInstNotIn []int `json:"custNumInstNotIn"`
	CustNumInstGt    *int  `json:"custNumInstGT"`
	CustNumInstGte   *int  `json:"custNumInstGTE"`
	CustNumInstLt    *int  `json:"custNumInstLT"`
	CustNumInstLte   *int  `json:"custNumInstLTE"`
	// cust_time_zone field predicates
	CustTimeZone      *time.Time   `json:"custTimeZone"`
	CustTimeZoneNeq   *time.Time   `json:"custTimeZoneNEQ"`
	CustTimeZoneIn    []*time.Time `json:"custTimeZoneIn"`
	CustTimeZoneNotIn []*time.Time `json:"custTimeZoneNotIn"`
	CustTimeZoneGt    *time.Time   `json:"custTimeZoneGT"`
	CustTimeZoneGte   *time.Time   `json:"custTimeZoneGTE"`
	CustTimeZoneLt    *time.Time   `json:"custTimeZoneLT"`
	CustTimeZoneLte   *time.Time   `json:"custTimeZoneLTE"`
	// id field predicates
	ID      *pulid.ID  `json:"id"`
	IDNeq   *pulid.ID  `json:"idNEQ"`
	IDIn    []pulid.ID `json:"idIn"`
	IDNotIn []pulid.ID `json:"idNotIn"`
	IDGt    *pulid.ID  `json:"idGT"`
	IDGte   *pulid.ID  `json:"idGTE"`
	IDLt    *pulid.ID  `json:"idLT"`
	IDLte   *pulid.ID  `json:"idLTE"`
	// Cust2Inst edge predicates
	HasCust2Inst     *bool                `json:"hasCust2Inst"`
	HasCust2InstWith []*MstInstWhereInput `json:"hasCust2InstWith"`
}

// MstInstWhereInput is used for filtering MstInst objects.
// Input was generated by ent.
type MstInstWhereInput struct {
	Not *MstInstWhereInput   `json:"not"`
	And []*MstInstWhereInput `json:"and"`
	Or  []*MstInstWhereInput `json:"or"`
	// created_at field predicates
	CreatedAt      *time.Time   `json:"createdAt"`
	CreatedAtNeq   *time.Time   `json:"createdAtNEQ"`
	CreatedAtIn    []*time.Time `json:"createdAtIn"`
	CreatedAtNotIn []*time.Time `json:"createdAtNotIn"`
	CreatedAtGt    *time.Time   `json:"createdAtGT"`
	CreatedAtGte   *time.Time   `json:"createdAtGTE"`
	CreatedAtLt    *time.Time   `json:"createdAtLT"`
	CreatedAtLte   *time.Time   `json:"createdAtLTE"`
	// updated_at field predicates
	UpdatedAt      *time.Time   `json:"updatedAt"`
	UpdatedAtNeq   *time.Time   `json:"updatedAtNEQ"`
	UpdatedAtIn    []*time.Time `json:"updatedAtIn"`
	UpdatedAtNotIn []*time.Time `json:"updatedAtNotIn"`
	UpdatedAtGt    *time.Time   `json:"updatedAtGT"`
	UpdatedAtGte   *time.Time   `json:"updatedAtGTE"`
	UpdatedAtLt    *time.Time   `json:"updatedAtLT"`
	UpdatedAtLte   *time.Time   `json:"updatedAtLTE"`
	// inst_code field predicates
	InstCode             *string  `json:"instCode"`
	InstCodeNeq          *string  `json:"instCodeNEQ"`
	InstCodeIn           []string `json:"instCodeIn"`
	InstCodeNotIn        []string `json:"instCodeNotIn"`
	InstCodeGt           *string  `json:"instCodeGT"`
	InstCodeGte          *string  `json:"instCodeGTE"`
	InstCodeLt           *string  `json:"instCodeLT"`
	InstCodeLte          *string  `json:"instCodeLTE"`
	InstCodeContains     *string  `json:"instCodeContains"`
	InstCodeHasPrefix    *string  `json:"instCodeHasPrefix"`
	InstCodeHasSuffix    *string  `json:"instCodeHasSuffix"`
	InstCodeEqualFold    *string  `json:"instCodeEqualFold"`
	InstCodeContainsFold *string  `json:"instCodeContainsFold"`
	// inst_name field predicates
	InstName             *string  `json:"instName"`
	InstNameNeq          *string  `json:"instNameNEQ"`
	InstNameIn           []string `json:"instNameIn"`
	InstNameNotIn        []string `json:"instNameNotIn"`
	InstNameGt           *string  `json:"instNameGT"`
	InstNameGte          *string  `json:"instNameGTE"`
	InstNameLt           *string  `json:"instNameLT"`
	InstNameLte          *string  `json:"instNameLTE"`
	InstNameContains     *string  `json:"instNameContains"`
	InstNameHasPrefix    *string  `json:"instNameHasPrefix"`
	InstNameHasSuffix    *string  `json:"instNameHasSuffix"`
	InstNameEqualFold    *string  `json:"instNameEqualFold"`
	InstNameContainsFold *string  `json:"instNameContainsFold"`
	// inst_short_name field predicates
	InstShortName             *string  `json:"instShortName"`
	InstShortNameNeq          *string  `json:"instShortNameNEQ"`
	InstShortNameIn           []string `json:"instShortNameIn"`
	InstShortNameNotIn        []string `json:"instShortNameNotIn"`
	InstShortNameGt           *string  `json:"instShortNameGT"`
	InstShortNameGte          *string  `json:"instShortNameGTE"`
	InstShortNameLt           *string  `json:"instShortNameLT"`
	InstShortNameLte          *string  `json:"instShortNameLTE"`
	InstShortNameContains     *string  `json:"instShortNameContains"`
	InstShortNameHasPrefix    *string  `json:"instShortNameHasPrefix"`
	InstShortNameHasSuffix    *string  `json:"instShortNameHasSuffix"`
	InstShortNameEqualFold    *string  `json:"instShortNameEqualFold"`
	InstShortNameContainsFold *string  `json:"instShortNameContainsFold"`
	// inst_address field predicates
	InstAddress             *string  `json:"instAddress"`
	InstAddressNeq          *string  `json:"instAddressNEQ"`
	InstAddressIn           []string `json:"instAddressIn"`
	InstAddressNotIn        []string `json:"instAddressNotIn"`
	InstAddressGt           *string  `json:"instAddressGT"`
	InstAddressGte          *string  `json:"instAddressGTE"`
	InstAddressLt           *string  `json:"instAddressLT"`
	InstAddressLte          *string  `json:"instAddressLTE"`
	InstAddressContains     *string  `json:"instAddressContains"`
	InstAddressHasPrefix    *string  `json:"instAddressHasPrefix"`
	InstAddressHasSuffix    *string  `json:"instAddressHasSuffix"`
	InstAddressEqualFold    *string  `json:"instAddressEqualFold"`
	InstAddressContainsFold *string  `json:"instAddressContainsFold"`
	// inst_place field predicates
	InstPlace             *string  `json:"instPlace"`
	InstPlaceNeq          *string  `json:"instPlaceNEQ"`
	InstPlaceIn           []string `json:"instPlaceIn"`
	InstPlaceNotIn        []string `json:"instPlaceNotIn"`
	InstPlaceGt           *string  `json:"instPlaceGT"`
	InstPlaceGte          *string  `json:"instPlaceGTE"`
	InstPlaceLt           *string  `json:"instPlaceLT"`
	InstPlaceLte          *string  `json:"instPlaceLTE"`
	InstPlaceContains     *string  `json:"instPlaceContains"`
	InstPlaceHasPrefix    *string  `json:"instPlaceHasPrefix"`
	InstPlaceHasSuffix    *string  `json:"instPlaceHasSuffix"`
	InstPlaceEqualFold    *string  `json:"instPlaceEqualFold"`
	InstPlaceContainsFold *string  `json:"instPlaceContainsFold"`
	// inst_state field predicates
	InstState             *string  `json:"instState"`
	InstStateNeq          *string  `json:"instStateNEQ"`
	InstStateIn           []string `json:"instStateIn"`
	InstStateNotIn        []string `json:"instStateNotIn"`
	InstStateGt           *string  `json:"instStateGT"`
	InstStateGte          *string  `json:"instStateGTE"`
	InstStateLt           *string  `json:"instStateLT"`
	InstStateLte          *string  `json:"instStateLTE"`
	InstStateContains     *string  `json:"instStateContains"`
	InstStateHasPrefix    *string  `json:"instStateHasPrefix"`
	InstStateHasSuffix    *string  `json:"instStateHasSuffix"`
	InstStateEqualFold    *string  `json:"instStateEqualFold"`
	InstStateContainsFold *string  `json:"instStateContainsFold"`
	// inst_pin field predicates
	InstPin             *string  `json:"instPin"`
	InstPinNeq          *string  `json:"instPinNEQ"`
	InstPinIn           []string `json:"instPinIn"`
	InstPinNotIn        []string `json:"instPinNotIn"`
	InstPinGt           *string  `json:"instPinGT"`
	InstPinGte          *string  `json:"instPinGTE"`
	InstPinLt           *string  `json:"instPinLT"`
	InstPinLte          *string  `json:"instPinLTE"`
	InstPinContains     *string  `json:"instPinContains"`
	InstPinHasPrefix    *string  `json:"instPinHasPrefix"`
	InstPinHasSuffix    *string  `json:"instPinHasSuffix"`
	InstPinEqualFold    *string  `json:"instPinEqualFold"`
	InstPinContainsFold *string  `json:"instPinContainsFold"`
	// inst_contact_person field predicates
	InstContactPerson             *string  `json:"instContactPerson"`
	InstContactPersonNeq          *string  `json:"instContactPersonNEQ"`
	InstContactPersonIn           []string `json:"instContactPersonIn"`
	InstContactPersonNotIn        []string `json:"instContactPersonNotIn"`
	InstContactPersonGt           *string  `json:"instContactPersonGT"`
	InstContactPersonGte          *string  `json:"instContactPersonGTE"`
	InstContactPersonLt           *string  `json:"instContactPersonLT"`
	InstContactPersonLte          *string  `json:"instContactPersonLTE"`
	InstContactPersonContains     *string  `json:"instContactPersonContains"`
	InstContactPersonHasPrefix    *string  `json:"instContactPersonHasPrefix"`
	InstContactPersonHasSuffix    *string  `json:"instContactPersonHasSuffix"`
	InstContactPersonEqualFold    *string  `json:"instContactPersonEqualFold"`
	InstContactPersonContainsFold *string  `json:"instContactPersonContainsFold"`
	// inst_phone field predicates
	InstPhone             *string  `json:"instPhone"`
	InstPhoneNeq          *string  `json:"instPhoneNEQ"`
	InstPhoneIn           []string `json:"instPhoneIn"`
	InstPhoneNotIn        []string `json:"instPhoneNotIn"`
	InstPhoneGt           *string  `json:"instPhoneGT"`
	InstPhoneGte          *string  `json:"instPhoneGTE"`
	InstPhoneLt           *string  `json:"instPhoneLT"`
	InstPhoneLte          *string  `json:"instPhoneLTE"`
	InstPhoneContains     *string  `json:"instPhoneContains"`
	InstPhoneHasPrefix    *string  `json:"instPhoneHasPrefix"`
	InstPhoneHasSuffix    *string  `json:"instPhoneHasSuffix"`
	InstPhoneEqualFold    *string  `json:"instPhoneEqualFold"`
	InstPhoneContainsFold *string  `json:"instPhoneContainsFold"`
	// inst_email field predicates
	InstEmail             *string  `json:"instEmail"`
	InstEmailNeq          *string  `json:"instEmailNEQ"`
	InstEmailIn           []string `json:"instEmailIn"`
	InstEmailNotIn        []string `json:"instEmailNotIn"`
	InstEmailGt           *string  `json:"instEmailGT"`
	InstEmailGte          *string  `json:"instEmailGTE"`
	InstEmailLt           *string  `json:"instEmailLT"`
	InstEmailLte          *string  `json:"instEmailLTE"`
	InstEmailContains     *string  `json:"instEmailContains"`
	InstEmailHasPrefix    *string  `json:"instEmailHasPrefix"`
	InstEmailHasSuffix    *string  `json:"instEmailHasSuffix"`
	InstEmailEqualFold    *string  `json:"instEmailEqualFold"`
	InstEmailContainsFold *string  `json:"instEmailContainsFold"`
	// inst_mobile field predicates
	InstMobile             *string  `json:"instMobile"`
	InstMobileNeq          *string  `json:"instMobileNEQ"`
	InstMobileIn           []string `json:"instMobileIn"`
	InstMobileNotIn        []string `json:"instMobileNotIn"`
	InstMobileGt           *string  `json:"instMobileGT"`
	InstMobileGte          *string  `json:"instMobileGTE"`
	InstMobileLt           *string  `json:"instMobileLT"`
	InstMobileLte          *string  `json:"instMobileLTE"`
	InstMobileContains     *string  `json:"instMobileContains"`
	InstMobileHasPrefix    *string  `json:"instMobileHasPrefix"`
	InstMobileHasSuffix    *string  `json:"instMobileHasSuffix"`
	InstMobileEqualFold    *string  `json:"instMobileEqualFold"`
	InstMobileContainsFold *string  `json:"instMobileContainsFold"`
	// inst_url field predicates
	InstURL             *string  `json:"instURL"`
	InstURLNeq          *string  `json:"instURLNEQ"`
	InstURLIn           []string `json:"instURLIn"`
	InstURLNotIn        []string `json:"instURLNotIn"`
	InstURLGt           *string  `json:"instURLGT"`
	InstURLGte          *string  `json:"instURLGTE"`
	InstURLLt           *string  `json:"instURLLT"`
	InstURLLte          *string  `json:"instURLLTE"`
	InstURLContains     *string  `json:"instURLContains"`
	InstURLHasPrefix    *string  `json:"instURLHasPrefix"`
	InstURLHasSuffix    *string  `json:"instURLHasSuffix"`
	InstURLEqualFold    *string  `json:"instURLEqualFold"`
	InstURLContainsFold *string  `json:"instURLContainsFold"`
	// inst_banner_1 field predicates
	InstBanner1             *string  `json:"instBanner1"`
	InstBanner1neq          *string  `json:"instBanner1NEQ"`
	InstBanner1In           []string `json:"instBanner1In"`
	InstBanner1NotIn        []string `json:"instBanner1NotIn"`
	InstBanner1gt           *string  `json:"instBanner1GT"`
	InstBanner1gte          *string  `json:"instBanner1GTE"`
	InstBanner1lt           *string  `json:"instBanner1LT"`
	InstBanner1lte          *string  `json:"instBanner1LTE"`
	InstBanner1Contains     *string  `json:"instBanner1Contains"`
	InstBanner1HasPrefix    *string  `json:"instBanner1HasPrefix"`
	InstBanner1HasSuffix    *string  `json:"instBanner1HasSuffix"`
	InstBanner1EqualFold    *string  `json:"instBanner1EqualFold"`
	InstBanner1ContainsFold *string  `json:"instBanner1ContainsFold"`
	// inst_banner_2 field predicates
	InstBanner2             *string  `json:"instBanner2"`
	InstBanner2neq          *string  `json:"instBanner2NEQ"`
	InstBanner2In           []string `json:"instBanner2In"`
	InstBanner2NotIn        []string `json:"instBanner2NotIn"`
	InstBanner2gt           *string  `json:"instBanner2GT"`
	InstBanner2gte          *string  `json:"instBanner2GTE"`
	InstBanner2lt           *string  `json:"instBanner2LT"`
	InstBanner2lte          *string  `json:"instBanner2LTE"`
	InstBanner2Contains     *string  `json:"instBanner2Contains"`
	InstBanner2HasPrefix    *string  `json:"instBanner2HasPrefix"`
	InstBanner2HasSuffix    *string  `json:"instBanner2HasSuffix"`
	InstBanner2EqualFold    *string  `json:"instBanner2EqualFold"`
	InstBanner2ContainsFold *string  `json:"instBanner2ContainsFold"`
	// inst_logo_url field predicates
	InstLogoURL             *string  `json:"instLogoURL"`
	InstLogoURLNeq          *string  `json:"instLogoURLNEQ"`
	InstLogoURLIn           []string `json:"instLogoURLIn"`
	InstLogoURLNotIn        []string `json:"instLogoURLNotIn"`
	InstLogoURLGt           *string  `json:"instLogoURLGT"`
	InstLogoURLGte          *string  `json:"instLogoURLGTE"`
	InstLogoURLLt           *string  `json:"instLogoURLLT"`
	InstLogoURLLte          *string  `json:"instLogoURLLTE"`
	InstLogoURLContains     *string  `json:"instLogoURLContains"`
	InstLogoURLHasPrefix    *string  `json:"instLogoURLHasPrefix"`
	InstLogoURLHasSuffix    *string  `json:"instLogoURLHasSuffix"`
	InstLogoURLEqualFold    *string  `json:"instLogoURLEqualFold"`
	InstLogoURLContainsFold *string  `json:"instLogoURLContainsFold"`
	// inst_is_active field predicates
	InstIsActive      *customtypes.IsActive  `json:"instIsActive"`
	InstIsActiveNeq   *customtypes.IsActive  `json:"instIsActiveNEQ"`
	InstIsActiveIn    []customtypes.IsActive `json:"instIsActiveIn"`
	InstIsActiveNotIn []customtypes.IsActive `json:"instIsActiveNotIn"`
	// inst_status field predicates
	InstStatus             *string  `json:"instStatus"`
	InstStatusNeq          *string  `json:"instStatusNEQ"`
	InstStatusIn           []string `json:"instStatusIn"`
	InstStatusNotIn        []string `json:"instStatusNotIn"`
	InstStatusGt           *string  `json:"instStatusGT"`
	InstStatusGte          *string  `json:"instStatusGTE"`
	InstStatusLt           *string  `json:"instStatusLT"`
	InstStatusLte          *string  `json:"instStatusLTE"`
	InstStatusContains     *string  `json:"instStatusContains"`
	InstStatusHasPrefix    *string  `json:"instStatusHasPrefix"`
	InstStatusHasSuffix    *string  `json:"instStatusHasSuffix"`
	InstStatusEqualFold    *string  `json:"instStatusEqualFold"`
	InstStatusContainsFold *string  `json:"instStatusContainsFold"`
	// inst_time_zone field predicates
	InstTimeZone      *time.Time   `json:"instTimeZone"`
	InstTimeZoneNeq   *time.Time   `json:"instTimeZoneNEQ"`
	InstTimeZoneIn    []*time.Time `json:"instTimeZoneIn"`
	InstTimeZoneNotIn []*time.Time `json:"instTimeZoneNotIn"`
	InstTimeZoneGt    *time.Time   `json:"instTimeZoneGT"`
	InstTimeZoneGte   *time.Time   `json:"instTimeZoneGTE"`
	InstTimeZoneLt    *time.Time   `json:"instTimeZoneLT"`
	InstTimeZoneLte   *time.Time   `json:"instTimeZoneLTE"`
	// customer_id field predicates
	CustomerID             *pulid.ID  `json:"customerID"`
	CustomerIDNeq          *pulid.ID  `json:"customerIDNEQ"`
	CustomerIDIn           []pulid.ID `json:"customerIDIn"`
	CustomerIDNotIn        []pulid.ID `json:"customerIDNotIn"`
	CustomerIDGt           *pulid.ID  `json:"customerIDGT"`
	CustomerIDGte          *pulid.ID  `json:"customerIDGTE"`
	CustomerIDLt           *pulid.ID  `json:"customerIDLT"`
	CustomerIDLte          *pulid.ID  `json:"customerIDLTE"`
	CustomerIDContains     *pulid.ID  `json:"customerIDContains"`
	CustomerIDHasPrefix    *pulid.ID  `json:"customerIDHasPrefix"`
	CustomerIDHasSuffix    *pulid.ID  `json:"customerIDHasSuffix"`
	CustomerIDEqualFold    *pulid.ID  `json:"customerIDEqualFold"`
	CustomerIDContainsFold *pulid.ID  `json:"customerIDContainsFold"`
	// id field predicates
	ID      *pulid.ID  `json:"id"`
	IDNeq   *pulid.ID  `json:"idNEQ"`
	IDIn    []pulid.ID `json:"idIn"`
	IDNotIn []pulid.ID `json:"idNotIn"`
	IDGt    *pulid.ID  `json:"idGT"`
	IDGte   *pulid.ID  `json:"idGTE"`
	IDLt    *pulid.ID  `json:"idLT"`
	IDLte   *pulid.ID  `json:"idLTE"`
	// InstfromCust edge predicates
	HasInstfromCust     *bool                    `json:"hasInstfromCust"`
	HasInstfromCustWith []*MstCustomerWhereInput `json:"hasInstfromCustWith"`
}
