// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package myeduate

import (
	"myeduate/ent/schema/pulid"
)

type CustData struct {
	CustomerName string   `json:"customer_name"`
	ID           pulid.ID `json:"id"`
}

type InstData struct {
	InstName string   `json:"Inst_name"`
	ID       pulid.ID `json:"id"`
}
