// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in myeduate/ent/runtime.go

const (
	Version = "v0.10.0"                                         // Version of ent codegen.
	Sum     = "h1:9cBomE1fh+WX34DPYQL7tDNAIvhKa3tXvwxuLyhYCMo=" // Sum of ent codegen.
)
