// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MstCustomersColumns holds the columns for the "mst_customers" table.
	MstCustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "cust_code", Type: field.TypeString, Unique: true},
		{Name: "cust_name", Type: field.TypeString, Unique: true},
		{Name: "cust_address", Type: field.TypeString},
		{Name: "cust_place", Type: field.TypeString},
		{Name: "cust_state", Type: field.TypeString},
		{Name: "cust_pin", Type: field.TypeString},
		{Name: "cust_contact_person", Type: field.TypeString},
		{Name: "cust_phone", Type: field.TypeString},
		{Name: "cust_email", Type: field.TypeString},
		{Name: "cust_mobile", Type: field.TypeString},
		{Name: "cust_url", Type: field.TypeString},
		{Name: "cust_banner_1", Type: field.TypeString},
		{Name: "cust_banner_2", Type: field.TypeString},
		{Name: "cust_logo_url", Type: field.TypeString},
		{Name: "cust_is_active", Type: field.TypeEnum, Enums: []string{"ACTIVE", "INACTIVE"}, Default: "ACTIVE"},
		{Name: "cust_status", Type: field.TypeString},
		{Name: "cust_num_inst", Type: field.TypeInt, Default: 0},
		{Name: "cust_time_zone", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "DATE"}},
	}
	// MstCustomersTable holds the schema information for the "mst_customers" table.
	MstCustomersTable = &schema.Table{
		Name:       "mst_customers",
		Columns:    MstCustomersColumns,
		PrimaryKey: []*schema.Column{MstCustomersColumns[0]},
	}
	// MstInstsColumns holds the columns for the "mst_insts" table.
	MstInstsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "inst_code", Type: field.TypeString, Unique: true},
		{Name: "inst_name", Type: field.TypeString},
		{Name: "inst_short_name", Type: field.TypeString},
		{Name: "inst_address", Type: field.TypeString},
		{Name: "inst_place", Type: field.TypeString},
		{Name: "inst_state", Type: field.TypeString},
		{Name: "inst_pin", Type: field.TypeString},
		{Name: "inst_contact_person", Type: field.TypeString},
		{Name: "inst_phone", Type: field.TypeString},
		{Name: "inst_email", Type: field.TypeString},
		{Name: "inst_mobile", Type: field.TypeString},
		{Name: "inst_url", Type: field.TypeString},
		{Name: "inst_banner_1", Type: field.TypeString},
		{Name: "inst_banner_2", Type: field.TypeString},
		{Name: "inst_logo_url", Type: field.TypeString},
		{Name: "inst_is_active", Type: field.TypeEnum, Enums: []string{"ACTIVE", "INACTIVE"}, Default: "ACTIVE"},
		{Name: "inst_status", Type: field.TypeString},
		{Name: "inst_time_zone", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "DATE"}},
		{Name: "customer_id", Type: field.TypeUUID, Nullable: true},
	}
	// MstInstsTable holds the schema information for the "mst_insts" table.
	MstInstsTable = &schema.Table{
		Name:       "mst_insts",
		Columns:    MstInstsColumns,
		PrimaryKey: []*schema.Column{MstInstsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "mst_insts_mst_customers_Cust2Inst",
				Columns:    []*schema.Column{MstInstsColumns[21]},
				RefColumns: []*schema.Column{MstCustomersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mstinst_inst_name_customer_id",
				Unique:  true,
				Columns: []*schema.Column{MstInstsColumns[4], MstInstsColumns[21]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MstCustomersTable,
		MstInstsTable,
	}
)

func init() {
	MstInstsTable.ForeignKeys[0].RefTable = MstCustomersTable
}
