// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"myeduate/ent/authstaff"
	"myeduate/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthStaffDelete is the builder for deleting a AuthStaff entity.
type AuthStaffDelete struct {
	config
	hooks    []Hook
	mutation *AuthStaffMutation
}

// Where appends a list predicates to the AuthStaffDelete builder.
func (asd *AuthStaffDelete) Where(ps ...predicate.AuthStaff) *AuthStaffDelete {
	asd.mutation.Where(ps...)
	return asd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (asd *AuthStaffDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(asd.hooks) == 0 {
		affected, err = asd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthStaffMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			asd.mutation = mutation
			affected, err = asd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(asd.hooks) - 1; i >= 0; i-- {
			if asd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = asd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, asd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (asd *AuthStaffDelete) ExecX(ctx context.Context) int {
	n, err := asd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (asd *AuthStaffDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: authstaff.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: authstaff.FieldID,
			},
		},
	}
	if ps := asd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, asd.driver, _spec)
}

// AuthStaffDeleteOne is the builder for deleting a single AuthStaff entity.
type AuthStaffDeleteOne struct {
	asd *AuthStaffDelete
}

// Exec executes the deletion query.
func (asdo *AuthStaffDeleteOne) Exec(ctx context.Context) error {
	n, err := asdo.asd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authstaff.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (asdo *AuthStaffDeleteOne) ExecX(ctx context.Context) {
	asdo.asd.ExecX(ctx)
}
