// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"fmt"
	"myeduate/ent/mstcustomer"
	"myeduate/ent/mstinst"
	"sync"
	"sync/atomic"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/schema"
	"github.com/99designs/gqlgen/graphql"
	"github.com/hashicorp/go-multierror"
	"golang.org/x/sync/semaphore"
)

// Noder wraps the basic Node method.
type Noder interface {
	Node(context.Context) (*Node, error)
}

// Node in the graph.
type Node struct {
	ID     int      `json:"id,omitempty"`     // node id.
	Type   string   `json:"type,omitempty"`   // node type.
	Fields []*Field `json:"fields,omitempty"` // node fields.
	Edges  []*Edge  `json:"edges,omitempty"`  // node edges.
}

// Field of a node.
type Field struct {
	Type  string `json:"type,omitempty"`  // field type.
	Name  string `json:"name,omitempty"`  // field name (as in struct).
	Value string `json:"value,omitempty"` // stringified value.
}

// Edges between two nodes.
type Edge struct {
	Type string `json:"type,omitempty"` // edge type.
	Name string `json:"name,omitempty"` // edge name.
	IDs  []int  `json:"ids,omitempty"`  // node ids (where this edge point to).
}

func (mc *MstCustomer) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     mc.ID,
		Type:   "MstCustomer",
		Fields: make([]*Field, 20),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	if buf, err = json.Marshal(mc.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustCode); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "cust_code",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustName); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "cust_name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustAddress); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "cust_address",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustPlace); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "cust_place",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustState); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "cust_state",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustPin); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "cust_pin",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustContactPerson); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "string",
		Name:  "cust_contact_person",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustPhone); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "string",
		Name:  "cust_phone",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustEmail); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "string",
		Name:  "cust_email",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustMobile); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "string",
		Name:  "cust_mobile",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustURL); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "string",
		Name:  "cust_url",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustBanner1); err != nil {
		return nil, err
	}
	node.Fields[13] = &Field{
		Type:  "string",
		Name:  "cust_banner_1",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustBanner2); err != nil {
		return nil, err
	}
	node.Fields[14] = &Field{
		Type:  "string",
		Name:  "cust_banner_2",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustLogoURL); err != nil {
		return nil, err
	}
	node.Fields[15] = &Field{
		Type:  "string",
		Name:  "cust_logo_url",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustIsActive); err != nil {
		return nil, err
	}
	node.Fields[16] = &Field{
		Type:  "customtypes.IsActive",
		Name:  "cust_is_active",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustStatus); err != nil {
		return nil, err
	}
	node.Fields[17] = &Field{
		Type:  "string",
		Name:  "cust_status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustNumInst); err != nil {
		return nil, err
	}
	node.Fields[18] = &Field{
		Type:  "int",
		Name:  "cust_num_inst",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mc.CustTimeZone); err != nil {
		return nil, err
	}
	node.Fields[19] = &Field{
		Type:  "time.Time",
		Name:  "cust_time_zone",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "MstInst",
		Name: "Cust2Inst",
	}
	err = mc.QueryCust2Inst().
		Select(mstinst.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (mi *MstInst) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     mi.ID,
		Type:   "MstInst",
		Fields: make([]*Field, 21),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	if buf, err = json.Marshal(mi.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstCode); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "inst_code",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstName); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "inst_name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstShortName); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "inst_short_name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstAddress); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "inst_address",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstPlace); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "inst_place",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstState); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "inst_state",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstPin); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "string",
		Name:  "inst_pin",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstContactPerson); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "string",
		Name:  "inst_contact_person",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstPhone); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "string",
		Name:  "inst_phone",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstEmail); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "string",
		Name:  "inst_email",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstMobile); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "string",
		Name:  "inst_mobile",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstURL); err != nil {
		return nil, err
	}
	node.Fields[13] = &Field{
		Type:  "string",
		Name:  "inst_url",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstBanner1); err != nil {
		return nil, err
	}
	node.Fields[14] = &Field{
		Type:  "string",
		Name:  "inst_banner_1",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstBanner2); err != nil {
		return nil, err
	}
	node.Fields[15] = &Field{
		Type:  "string",
		Name:  "inst_banner_2",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstLogoURL); err != nil {
		return nil, err
	}
	node.Fields[16] = &Field{
		Type:  "string",
		Name:  "inst_logo_url",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstIsActive); err != nil {
		return nil, err
	}
	node.Fields[17] = &Field{
		Type:  "customtypes.IsActive",
		Name:  "inst_is_active",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstStatus); err != nil {
		return nil, err
	}
	node.Fields[18] = &Field{
		Type:  "string",
		Name:  "inst_status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.InstTimeZone); err != nil {
		return nil, err
	}
	node.Fields[19] = &Field{
		Type:  "time.Time",
		Name:  "inst_time_zone",
		Value: string(buf),
	}
	if buf, err = json.Marshal(mi.CustomerID); err != nil {
		return nil, err
	}
	node.Fields[20] = &Field{
		Type:  "int",
		Name:  "customer_id",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "MstCustomer",
		Name: "InstfromCust",
	}
	err = mi.QueryInstfromCust().
		Select(mstcustomer.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (c *Client) Node(ctx context.Context, id int) (*Node, error) {
	n, err := c.Noder(ctx, id)
	if err != nil {
		return nil, err
	}
	return n.Node(ctx)
}

var errNodeInvalidID = &NotFoundError{"node"}

// NodeOption allows configuring the Noder execution using functional options.
type NodeOption func(*nodeOptions)

// WithNodeType sets the node Type resolver function (i.e. the table to query).
// If was not provided, the table will be derived from the universal-id
// configuration as described in: https://entgo.io/docs/migrate/#universal-ids.
func WithNodeType(f func(context.Context, int) (string, error)) NodeOption {
	return func(o *nodeOptions) {
		o.nodeType = f
	}
}

// WithFixedNodeType sets the Type of the node to a fixed value.
func WithFixedNodeType(t string) NodeOption {
	return WithNodeType(func(context.Context, int) (string, error) {
		return t, nil
	})
}

type nodeOptions struct {
	nodeType func(context.Context, int) (string, error)
}

func (c *Client) newNodeOpts(opts []NodeOption) *nodeOptions {
	nopts := &nodeOptions{}
	for _, opt := range opts {
		opt(nopts)
	}
	if nopts.nodeType == nil {
		nopts.nodeType = func(ctx context.Context, id int) (string, error) {
			return c.tables.nodeType(ctx, c.driver, id)
		}
	}
	return nopts
}

// Noder returns a Node by its id. If the NodeType was not provided, it will
// be derived from the id value according to the universal-id configuration.
//
//		c.Noder(ctx, id)
//		c.Noder(ctx, id, ent.WithNodeType(pet.Table))
//
func (c *Client) Noder(ctx context.Context, id int, opts ...NodeOption) (_ Noder, err error) {
	defer func() {
		if IsNotFound(err) {
			err = multierror.Append(err, entgql.ErrNodeNotFound(id))
		}
	}()
	table, err := c.newNodeOpts(opts).nodeType(ctx, id)
	if err != nil {
		return nil, err
	}
	return c.noder(ctx, table, id)
}

func (c *Client) noder(ctx context.Context, table string, id int) (Noder, error) {
	switch table {
	case mstcustomer.Table:
		n, err := c.MstCustomer.Query().
			Where(mstcustomer.ID(id)).
			CollectFields(ctx, "MstCustomer").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case mstinst.Table:
		n, err := c.MstInst.Query().
			Where(mstinst.ID(id)).
			CollectFields(ctx, "MstInst").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	default:
		return nil, fmt.Errorf("cannot resolve noder from table %q: %w", table, errNodeInvalidID)
	}
}

func (c *Client) Noders(ctx context.Context, ids []int, opts ...NodeOption) ([]Noder, error) {
	switch len(ids) {
	case 1:
		noder, err := c.Noder(ctx, ids[0], opts...)
		if err != nil {
			return nil, err
		}
		return []Noder{noder}, nil
	case 0:
		return []Noder{}, nil
	}

	noders := make([]Noder, len(ids))
	errors := make([]error, len(ids))
	tables := make(map[string][]int)
	id2idx := make(map[int][]int, len(ids))
	nopts := c.newNodeOpts(opts)
	for i, id := range ids {
		table, err := nopts.nodeType(ctx, id)
		if err != nil {
			errors[i] = err
			continue
		}
		tables[table] = append(tables[table], id)
		id2idx[id] = append(id2idx[id], i)
	}

	for table, ids := range tables {
		nodes, err := c.noders(ctx, table, ids)
		if err != nil {
			for _, id := range ids {
				for _, idx := range id2idx[id] {
					errors[idx] = err
				}
			}
		} else {
			for i, id := range ids {
				for _, idx := range id2idx[id] {
					noders[idx] = nodes[i]
				}
			}
		}
	}

	for i, id := range ids {
		if errors[i] == nil {
			if noders[i] != nil {
				continue
			}
			errors[i] = entgql.ErrNodeNotFound(id)
		} else if IsNotFound(errors[i]) {
			errors[i] = multierror.Append(errors[i], entgql.ErrNodeNotFound(id))
		}
		ctx := graphql.WithPathContext(ctx,
			graphql.NewPathWithIndex(i),
		)
		graphql.AddError(ctx, errors[i])
	}
	return noders, nil
}

func (c *Client) noders(ctx context.Context, table string, ids []int) ([]Noder, error) {
	noders := make([]Noder, len(ids))
	idmap := make(map[int][]*Noder, len(ids))
	for i, id := range ids {
		idmap[id] = append(idmap[id], &noders[i])
	}
	switch table {
	case mstcustomer.Table:
		nodes, err := c.MstCustomer.Query().
			Where(mstcustomer.IDIn(ids...)).
			CollectFields(ctx, "MstCustomer").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case mstinst.Table:
		nodes, err := c.MstInst.Query().
			Where(mstinst.IDIn(ids...)).
			CollectFields(ctx, "MstInst").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	default:
		return nil, fmt.Errorf("cannot resolve noders from table %q: %w", table, errNodeInvalidID)
	}
	return noders, nil
}

type tables struct {
	once  sync.Once
	sem   *semaphore.Weighted
	value atomic.Value
}

func (t *tables) nodeType(ctx context.Context, drv dialect.Driver, id int) (string, error) {
	tables, err := t.Load(ctx, drv)
	if err != nil {
		return "", err
	}
	idx := int(id / (1<<32 - 1))
	if idx < 0 || idx >= len(tables) {
		return "", fmt.Errorf("cannot resolve table from id %v: %w", id, errNodeInvalidID)
	}
	return tables[idx], nil
}

func (t *tables) Load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	t.once.Do(func() { t.sem = semaphore.NewWeighted(1) })
	if err := t.sem.Acquire(ctx, 1); err != nil {
		return nil, err
	}
	defer t.sem.Release(1)
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	tables, err := t.load(ctx, drv)
	if err == nil {
		t.value.Store(tables)
	}
	return tables, err
}

func (*tables) load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	rows := &sql.Rows{}
	query, args := sql.Dialect(drv.Dialect()).
		Select("type").
		From(sql.Table(schema.TypeTable)).
		OrderBy(sql.Asc("id")).
		Query()
	if err := drv.Query(ctx, query, args, rows); err != nil {
		return nil, err
	}
	defer rows.Close()
	var tables []string
	return tables, sql.ScanSlice(rows, &tables)
}
