// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"myeduate/ent/mstcustomer"
	"myeduate/ent/mstinst"
	"myeduate/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mstcustomerMixin := schema.MstCustomer{}.Mixin()
	mstcustomerMixinFields0 := mstcustomerMixin[0].Fields()
	_ = mstcustomerMixinFields0
	mstcustomerFields := schema.MstCustomer{}.Fields()
	_ = mstcustomerFields
	// mstcustomerDescCreatedAt is the schema descriptor for created_at field.
	mstcustomerDescCreatedAt := mstcustomerMixinFields0[0].Descriptor()
	// mstcustomer.DefaultCreatedAt holds the default value on creation for the created_at field.
	mstcustomer.DefaultCreatedAt = mstcustomerDescCreatedAt.Default.(func() time.Time)
	// mstcustomerDescUpdatedAt is the schema descriptor for updated_at field.
	mstcustomerDescUpdatedAt := mstcustomerMixinFields0[1].Descriptor()
	// mstcustomer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mstcustomer.DefaultUpdatedAt = mstcustomerDescUpdatedAt.Default.(func() time.Time)
	// mstcustomer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mstcustomer.UpdateDefaultUpdatedAt = mstcustomerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mstcustomerDescCustName is the schema descriptor for cust_name field.
	mstcustomerDescCustName := mstcustomerFields[1].Descriptor()
	// mstcustomer.CustNameValidator is a validator for the "cust_name" field. It is called by the builders before save.
	mstcustomer.CustNameValidator = mstcustomerDescCustName.Validators[0].(func(string) error)
	// mstcustomerDescCustNumInst is the schema descriptor for cust_num_inst field.
	mstcustomerDescCustNumInst := mstcustomerFields[16].Descriptor()
	// mstcustomer.DefaultCustNumInst holds the default value on creation for the cust_num_inst field.
	mstcustomer.DefaultCustNumInst = mstcustomerDescCustNumInst.Default.(int)
	mstinstMixin := schema.MstInst{}.Mixin()
	mstinstMixinFields0 := mstinstMixin[0].Fields()
	_ = mstinstMixinFields0
	mstinstFields := schema.MstInst{}.Fields()
	_ = mstinstFields
	// mstinstDescCreatedAt is the schema descriptor for created_at field.
	mstinstDescCreatedAt := mstinstMixinFields0[0].Descriptor()
	// mstinst.DefaultCreatedAt holds the default value on creation for the created_at field.
	mstinst.DefaultCreatedAt = mstinstDescCreatedAt.Default.(func() time.Time)
	// mstinstDescUpdatedAt is the schema descriptor for updated_at field.
	mstinstDescUpdatedAt := mstinstMixinFields0[1].Descriptor()
	// mstinst.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mstinst.DefaultUpdatedAt = mstinstDescUpdatedAt.Default.(func() time.Time)
	// mstinst.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mstinst.UpdateDefaultUpdatedAt = mstinstDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mstinstDescInstName is the schema descriptor for inst_name field.
	mstinstDescInstName := mstinstFields[1].Descriptor()
	// mstinst.InstNameValidator is a validator for the "inst_name" field. It is called by the builders before save.
	mstinst.InstNameValidator = mstinstDescInstName.Validators[0].(func(string) error)
}
