// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package msgchannelmessage

import (
	"time"
)

const (
	// Label holds the string label denoting the msgchannelmessage type in the database.
	Label = "msg_channel_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldMsgDate holds the string denoting the msg_date field in the database.
	FieldMsgDate = "msg_date"
	// FieldMsgIsExpiry holds the string denoting the msg_is_expiry field in the database.
	FieldMsgIsExpiry = "msg_is_expiry"
	// FieldMsgExpiryDate holds the string denoting the msg_expiry_date field in the database.
	FieldMsgExpiryDate = "msg_expiry_date"
	// FieldMsgIsText holds the string denoting the msg_is_text field in the database.
	FieldMsgIsText = "msg_is_text"
	// FieldMsgContent holds the string denoting the msg_content field in the database.
	FieldMsgContent = "msg_content"
	// FieldMsgMediaType holds the string denoting the msg_media_type field in the database.
	FieldMsgMediaType = "msg_media_type"
	// FieldMsgMediaContent holds the string denoting the msg_media_content field in the database.
	FieldMsgMediaContent = "msg_media_content"
	// FieldMsgActive holds the string denoting the msg_active field in the database.
	FieldMsgActive = "msg_active"
	// FieldMsgIsIndividual holds the string denoting the msg_is_individual field in the database.
	FieldMsgIsIndividual = "msg_is_individual"
	// FieldMsgRecvOrSent holds the string denoting the msg_recv_or_sent field in the database.
	FieldMsgRecvOrSent = "msg_recv_or_sent"
	// Table holds the table name of the msgchannelmessage in the database.
	Table = "msg_channel_messages"
)

// Columns holds all SQL columns for msgchannelmessage fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldMsgDate,
	FieldMsgIsExpiry,
	FieldMsgExpiryDate,
	FieldMsgIsText,
	FieldMsgContent,
	FieldMsgMediaType,
	FieldMsgMediaContent,
	FieldMsgActive,
	FieldMsgIsIndividual,
	FieldMsgRecvOrSent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultMsgDate holds the default value on creation for the "msg_date" field.
	DefaultMsgDate func() time.Time
	// DefaultMsgIsExpiry holds the default value on creation for the "msg_is_expiry" field.
	DefaultMsgIsExpiry bool
	// DefaultMsgExpiryDate holds the default value on creation for the "msg_expiry_date" field.
	DefaultMsgExpiryDate func() time.Time
	// DefaultMsgIsText holds the default value on creation for the "msg_is_text" field.
	DefaultMsgIsText bool
	// DefaultMsgActive holds the default value on creation for the "msg_active" field.
	DefaultMsgActive bool
)
