// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package authparent

import (
	"time"
)

const (
	// Label holds the string label denoting the authparent type in the database.
	Label = "auth_parent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldParentFirstName holds the string denoting the parent_first_name field in the database.
	FieldParentFirstName = "parent_first_name"
	// FieldParentMiddleName holds the string denoting the parent_middle_name field in the database.
	FieldParentMiddleName = "parent_middle_name"
	// FieldParentLastName holds the string denoting the parent_last_name field in the database.
	FieldParentLastName = "parent_last_name"
	// Table holds the table name of the authparent in the database.
	Table = "auth_parents"
)

// Columns holds all SQL columns for authparent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldParentFirstName,
	FieldParentMiddleName,
	FieldParentLastName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ParentFirstNameValidator is a validator for the "parent_first_name" field. It is called by the builders before save.
	ParentFirstNameValidator func(string) error
)
